name: CoHive
description: AI tool interface with hexagonal breadcrumb navigation for Databricks workflows

# Command to install dependencies and run the app
command:
  - sh
  - -c
  - |
    # Install Python dependencies
    pip install -r requirements.txt
    
    # Install Node dependencies (including dev dependencies)
    npm install
    
    # Build React app for production using npx to ensure vite is found
    npx vite build
    
    # Start Flask API in background
    cd api && python databricks_files.py &
    
    # Wait a moment for Flask to start
    sleep 2
    
    # Serve the built React app
    npx serve -s build -l 8080

# Port configuration
port: 8080

# Environment variables
env:
  - name: NODE_ENV
    value: production
  - name: VITE_DATABRICKS_ENABLED
    value: "true"
  - name: API_PORT
    value: "5000"
  - name: PYTHONUNBUFFERED
    value: "1"

# Resource allocation
resources:
  memory: 4Gi
  cpu: 2